version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  build:
    docker:
      - image: cimg/node:19.0.1
    steps:
      - checkout
      - run: echo "build step"
      - run: cd client && npm build
  test:
    docker:
      - image: cimg/node:19.0.1
    steps:
      - checkout
      - run: echo "test step"
      - run: cd client && npm test
  coverage:
    docker:
      - image: cimg/node:19.0.1
    steps:
      - browser-tools/install-browser-tools
      - run: cd client && npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: jest --collectCoverage=true
      - store_artifacts:
          path: coverage
workflows:
  version: 2
  buildcheck:
    jobs:
      - build
      - test
      - coverage
