version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "build step"
      - run: npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "test step"
      - run: npm run test
  coverage:
    docker:
      - image: circleci/node:8.9
    steps:
      - browser-tools/install-browser-tools
      - run: npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: jest --collectCoverage=true
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  buildcheck:
    jobs:
      - build
      - test
      - coverage
